spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connection-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONES}
    register-with-eureka: true

jwt:
  secretKey: ${JWT_SECRET_KEY}