spring.application.name=connection-service
server.port=${SERVER_PORT}

spring.neo4j.uri=${DB_URL}
spring.neo4j.authentication.username=${DB_USERNAME}
spring.neo4j.authentication.password=${DB_PASSWORD}
server.servlet.context.path=${SERVER_SERVLET_CONTEXT_PATH}